spring.application.name=HackHub

# Database H2 in-memory
spring.datasource.url=jdbc:h2:mem:hackhub;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console web H2, raggiungibile su http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate ricrea lo schema a ogni avvio, utile in sviluppo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

#Google
google.credentials.path=src/test/resources/client_secret.json